export const productsData = {
  electronics: [
    {
      id: 1,
      name: "Wireless Earbuds TWS Pro",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 599,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585386959984-a41552231658",
      isTopProduct: true,
      similarProducts: [
        {
          id: 3,
          name: "Wired In-Ear Earphones Bulk",
          category: "electronics",
          subcategory: "audio & headphones",
          price: 149,
          minQty: 200,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf",
        },
        {
          id: 4,
          name: "Bluetooth Neckband Headset",
          category: "electronics",
          subcategory: "audio & headphones",
          price: 699,
          minQty: 60,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d",
        },
      ],
    },
    {
      id: 2,
      name: "Noise Cancelling Headphones",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 1499,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd",
      isTopProduct: true,
      similarProducts: [
        {
          id: 5,
          name: "Studio Monitor Headphones",
          category: "electronics",
          subcategory: "audio & headphones",
          price: 2199,
          minQty: 10,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a",
        },
        {
          id: 6,
          name: "Portable Bluetooth Speaker",
          category: "electronics",
          subcategory: "audio & headphones",
          price: 1199,
          minQty: 25,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1545454675-3531b543be5d",
        },
      ],
    },
    {
      id: 3,
      name: "Wired In-Ear Earphones Bulk",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 149,
      minQty: 200,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf",
    },
    {
      id: 4,
      name: "Bluetooth Neckband Headset",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 699,
      minQty: 60,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d",
    },
    {
      id: 5,
      name: "Studio Monitor Headphones",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 2199,
      minQty: 10,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a",
    },
    {
      id: 6,
      name: "Portable Bluetooth Speaker",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 1199,
      minQty: 25,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1545454675-3531b543be5d",
    },
    {
      id: 7,
      name: "Soundbar 2.1 Channel",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 4999,
      minQty: 5,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b",
    },
    {
      id: 8,
      name: "Gaming Headset Mic",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 1299,
      minQty: 15,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1555617117-08d6c5f4b6b8",
    },
    {
      id: 9,
      name: "True Wireless Earbuds Mini",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 499,
      minQty: 80,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1590658165737-15a047b6ed1d",
    },
    {
      id: 10,
      name: "Over-Ear Headphones Foldable",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 999,
      minQty: 30,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    },

    {
      id: 11,
      name: "Laptop Cooling Pad",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 399,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587202372775-989c1b1a7b4c",
      isTopProduct: true,
      similarProducts: [
        {
          id: 13,
          name: "Wireless Mouse Bulk",
          category: "electronics",
          subcategory: "laptops & computers",
          price: 299,
          minQty: 100,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
        },
        {
          id: 14,
          name: "Laptop Stand Adjustable",
          category: "electronics",
          subcategory: "laptops & computers",
          price: 699,
          minQty: 40,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
      ],
    },
    {
      id: 12,
      name: "USB-C Hub 7 in 1",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 899,
      minQty: 25,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1587206668289-c21d4c2c92e4",
      isTopProduct: true,
      similarProducts: [
        {
          id: 15,
          name: "HD Webcam 1080p",
          category: "electronics",
          subcategory: "laptops & computers",
          price: 1199,
          minQty: 15,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9",
        },
        {
          id: 16,
          name: "External SSD 1TB",
          category: "electronics",
          subcategory: "laptops & computers",
          price: 7999,
          minQty: 5,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1618472609777-b038f1f04b8d",
        },
      ],
    },
    {
      id: 13,
      name: "Wireless Mouse Bulk",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 299,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
    },
    {
      id: 14,
      name: "Laptop Stand Adjustable",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 699,
      minQty: 40,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 15,
      name: "HD Webcam 1080p",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 1199,
      minQty: 15,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9",
    },
    {
      id: 16,
      name: "External SSD 1TB",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 7999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1618472609777-b038f1f04b8d",
    },
    {
      id: 17,
      name: "USB Flash Drive 64GB",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 249,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa",
    },
    {
      id: 18,
      name: "Laptop Backpack Wholesale",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 899,
      minQty: 30,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
    },
    {
      id: 19,
      name: "HDMI Cable Pack",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 149,
      minQty: 250,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 20,
      name: "Laptop Cleaning Kit",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586941975096-4e0a5cfcf0c4",
    },

    {
      id: 21,
      name: "CCTV Camera 1080p",
      category: "electronics",
      subcategory: "cameras & security",
      price: 1299,
      minQty: 10,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581091870627-3a6c8c9f7f47",
      isTopProduct: true,
      similarProducts: [
        {
          id: 23,
          name: "Video Doorbell Camera",
          category: "electronics",
          subcategory: "cameras & security",
          price: 2499,
          minQty: 5,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1558002038-1055907df827",
        },
        {
          id: 24,
          name: "DVR Recorder 8 Channel",
          category: "electronics",
          subcategory: "cameras & security",
          price: 6999,
          minQty: 2,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1551879400-111a9087cd86",
        },
      ],
    },
    {
      id: 22,
      name: "WiFi Smart Camera",
      category: "electronics",
      subcategory: "cameras & security",
      price: 1699,
      minQty: 10,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1580894894513-ea9f8b6b5d6c",
      isTopProduct: true,
      similarProducts: [
        {
          id: 25,
          name: "CCTV Power Adapter Pack",
          category: "electronics",
          subcategory: "cameras & security",
          price: 299,
          minQty: 50,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
        {
          id: 26,
          name: "Security Alarm Kit",
          category: "electronics",
          subcategory: "cameras & security",
          price: 3499,
          minQty: 5,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1581091870627-3a6c8c9f7f47",
        },
      ],
    },
    {
      id: 23,
      name: "Video Doorbell Camera",
      category: "electronics",
      subcategory: "cameras & security",
      price: 2499,
      minQty: 5,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827",
    },
    {
      id: 24,
      name: "DVR Recorder 8 Channel",
      category: "electronics",
      subcategory: "cameras & security",
      price: 6999,
      minQty: 2,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1551879400-111a9087cd86",
    },
    {
      id: 25,
      name: "CCTV Power Adapter Pack",
      category: "electronics",
      subcategory: "cameras & security",
      price: 299,
      minQty: 50,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 26,
      name: "Security Alarm Kit",
      category: "electronics",
      subcategory: "cameras & security",
      price: 3499,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581091870627-3a6c8c9f7f47",
    },
    {
      id: 27,
      name: "Motion Sensor Detector",
      category: "electronics",
      subcategory: "cameras & security",
      price: 499,
      minQty: 30,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3",
    },
    {
      id: 28,
      name: "Smart Lock Keypad",
      category: "electronics",
      subcategory: "cameras & security",
      price: 3999,
      minQty: 5,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827",
    },
    {
      id: 29,
      name: "Micro SD Card 128GB",
      category: "electronics",
      subcategory: "cameras & security",
      price: 799,
      minQty: 25,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa",
    },
    {
      id: 30,
      name: "Camera Mount Bracket",
      category: "electronics",
      subcategory: "cameras & security",
      price: 199,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827",
    },

    {
      id: 31,
      name: "LED Monitor 24 inch",
      category: "electronics",
      subcategory: "monitors",
      price: 7999,
      minQty: 5,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
      isTopProduct: true,
      similarProducts: [
        {
          id: 33,
          name: "Curved Monitor 32 inch",
          category: "electronics",
          subcategory: "monitors",
          price: 18999,
          minQty: 2,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
        {
          id: 35,
          name: "Monitor Wall Mount",
          category: "electronics",
          subcategory: "monitors",
          price: 899,
          minQty: 20,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
      ],
    },
    {
      id: 32,
      name: "LED Monitor 27 inch",
      category: "electronics",
      subcategory: "monitors",
      price: 10999,
      minQty: 3,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
      isTopProduct: true,
      similarProducts: [
        {
          id: 34,
          name: "Portable Monitor 15.6 inch",
          category: "electronics",
          subcategory: "monitors",
          price: 12999,
          minQty: 2,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
        {
          id: 36,
          name: "HDMI to VGA Adapter",
          category: "electronics",
          subcategory: "monitors",
          price: 249,
          minQty: 100,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
        },
      ],
    },
    {
      id: 33,
      name: "Curved Monitor 32 inch",
      category: "electronics",
      subcategory: "monitors",
      price: 18999,
      minQty: 2,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 34,
      name: "Portable Monitor 15.6 inch",
      category: "electronics",
      subcategory: "monitors",
      price: 12999,
      minQty: 2,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 35,
      name: "Monitor Wall Mount",
      category: "electronics",
      subcategory: "monitors",
      price: 899,
      minQty: 20,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 36,
      name: "HDMI to VGA Adapter",
      category: "electronics",
      subcategory: "monitors",
      price: 249,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 37,
      name: "DisplayPort Cable Pack",
      category: "electronics",
      subcategory: "monitors",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 38,
      name: "Monitor Cleaning Wipes",
      category: "electronics",
      subcategory: "monitors",
      price: 99,
      minQty: 400,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586941975096-4e0a5cfcf0c4",
    },
    {
      id: 39,
      name: "USB Display Adapter",
      category: "electronics",
      subcategory: "monitors",
      price: 1299,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 40,
      name: "Anti-Glare Screen Protector",
      category: "electronics",
      subcategory: "monitors",
      price: 299,
      minQty: 200,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },

    {
      id: 41,
      name: "Mechanical Keyboard RGB",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 1999,
      minQty: 15,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
      isTopProduct: true,
      similarProducts: [
        {
          id: 43,
          name: "Gaming Mouse RGB",
          category: "electronics",
          subcategory: "keyboards & mice",
          price: 599,
          minQty: 40,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
        },
        {
          id: 44,
          name: "Keyboard Wrist Rest",
          category: "electronics",
          subcategory: "keyboards & mice",
          price: 249,
          minQty: 100,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        },
      ],
    },
    {
      id: 42,
      name: "Wireless Keyboard Mouse Combo",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 899,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
      isTopProduct: true,
      similarProducts: [
        {
          id: 45,
          name: "Mouse Pad XL",
          category: "electronics",
          subcategory: "keyboards & mice",
          price: 199,
          minQty: 150,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        },
        {
          id: 46,
          name: "Numeric Keypad USB",
          category: "electronics",
          subcategory: "keyboards & mice",
          price: 299,
          minQty: 80,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        },
      ],
    },
    {
      id: 43,
      name: "Gaming Mouse RGB",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 599,
      minQty: 40,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
    },
    {
      id: 44,
      name: "Keyboard Wrist Rest",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 249,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 45,
      name: "Mouse Pad XL",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 46,
      name: "Numeric Keypad USB",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 299,
      minQty: 80,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 47,
      name: "Silent Click Wireless Mouse",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 349,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
    },
    {
      id: 48,
      name: "USB Keyboard Bulk",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 399,
      minQty: 60,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 49,
      name: "Ergonomic Vertical Mouse",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 799,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527814050087-3793815479db",
    },
    {
      id: 50,
      name: "Keyboard Cleaning Brush",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 99,
      minQty: 300,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586941975096-4e0a5cfcf0c4",
    },

    {
      id: 51,
      name: "Power Bank 20000mAh",
      category: "electronics",
      subcategory: "power & batteries",
      price: 899,
      minQty: 40,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1580910051074-3eb694886505",
      isTopProduct: true,
      similarProducts: [
        {
          id: 52,
          name: "Fast Charger 33W",
          category: "electronics",
          subcategory: "power & batteries",
          price: 499,
          minQty: 80,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        },
        {
          id: 53,
          name: "USB-C Cable 1m Pack",
          category: "electronics",
          subcategory: "power & batteries",
          price: 99,
          minQty: 500,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
        },
      ],
    },
    {
      id: 52,
      name: "Fast Charger 33W",
      category: "electronics",
      subcategory: "power & batteries",
      price: 499,
      minQty: 80,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
      isTopProduct: true,
      similarProducts: [
        {
          id: 54,
          name: "Laptop Adapter 65W",
          category: "electronics",
          subcategory: "power & batteries",
          price: 1499,
          minQty: 20,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
        },
        {
          id: 55,
          name: "AA Battery Pack (40 pcs)",
          category: "electronics",
          subcategory: "power & batteries",
          price: 399,
          minQty: 100,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1615220677800-7a25f56c7cc8",
        },
      ],
    },
    {
      id: 53,
      name: "USB-C Cable 1m Pack",
      category: "electronics",
      subcategory: "power & batteries",
      price: 99,
      minQty: 500,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 54,
      name: "Laptop Adapter 65W",
      category: "electronics",
      subcategory: "power & batteries",
      price: 1499,
      minQty: 20,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 55,
      name: "AA Battery Pack (40 pcs)",
      category: "electronics",
      subcategory: "power & batteries",
      price: 399,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1615220677800-7a25f56c7cc8",
    },
    {
      id: 56,
      name: "Rechargeable Battery Charger",
      category: "electronics",
      subcategory: "power & batteries",
      price: 899,
      minQty: 30,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1580910051074-3eb694886505",
    },
    {
      id: 57,
      name: "Car Charger Dual USB",
      category: "electronics",
      subcategory: "power & batteries",
      price: 249,
      minQty: 150,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 58,
      name: "Extension Board 6 Socket",
      category: "electronics",
      subcategory: "power & batteries",
      price: 349,
      minQty: 60,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 59,
      name: "Surge Protector Strip",
      category: "electronics",
      subcategory: "power & batteries",
      price: 699,
      minQty: 25,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 60,
      name: "Battery Storage Case",
      category: "electronics",
      subcategory: "power & batteries",
      price: 149,
      minQty: 200,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1615220677800-7a25f56c7cc8",
    },
    {
      id: 52,
      name: "Fast Charger 33W",
      category: "electronics",
      subcategory: "power & batteries",
      price: 499,
      minQty: 80,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 53,
      name: "USB-C Cable 1m Pack",
      category: "electronics",
      subcategory: "power & batteries",
      price: 99,
      minQty: 500,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 54,
      name: "Laptop Adapter 65W",
      category: "electronics",
      subcategory: "power & batteries",
      price: 1499,
      minQty: 20,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 55,
      name: "AA Battery Pack (40 pcs)",
      category: "electronics",
      subcategory: "power & batteries",
      price: 399,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1615220677800-7a25f56c7cc8",
    },
    {
      id: 56,
      name: "Rechargeable Battery Charger",
      category: "electronics",
      subcategory: "power & batteries",
      price: 899,
      minQty: 30,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1580910051074-3eb694886505",
    },
    {
      id: 57,
      name: "Car Charger Dual USB",
      category: "electronics",
      subcategory: "power & batteries",
      price: 249,
      minQty: 150,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 58,
      name: "Extension Board 6 Socket",
      category: "electronics",
      subcategory: "power & batteries",
      price: 349,
      minQty: 60,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 59,
      name: "Surge Protector Strip",
      category: "electronics",
      subcategory: "power & batteries",
      price: 699,
      minQty: 25,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    },
    {
      id: 60,
      name: "Battery Storage Case",
      category: "electronics",
      subcategory: "power & batteries",
      price: 149,
      minQty: 200,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1615220677800-7a25f56c7cc8",
    },
  ],

  apparel: [
    {
      id: 61,
      name: "Men Cotton T-Shirts Pack",
      category: "apparel",
      subcategory: "men wear",
      price: 299,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
      isTopProduct: true,
      similarProducts: [
        {
          id: 63,
          name: "Men Formal Shirt Wholesale",
          category: "apparel",
          subcategory: "men wear",
          price: 699,
          minQty: 60,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1520975682071-a8a463a1c9d2",
        },
        {
          id: 64,
          name: "Men Polo T-Shirts Bulk",
          category: "apparel",
          subcategory: "men wear",
          price: 399,
          minQty: 80,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
        },
      ],
    },
    {
      id: 62,
      name: "Men Denim Jeans Bulk",
      category: "apparel",
      subcategory: "men wear",
      price: 899,
      minQty: 70,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
      isTopProduct: true,
      similarProducts: [
        {
          id: 65,
          name: "Men Hoodie Winter",
          category: "apparel",
          subcategory: "men wear",
          price: 999,
          minQty: 40,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
        },
        {
          id: 66,
          name: "Men Track Pants Wholesale",
          category: "apparel",
          subcategory: "men wear",
          price: 549,
          minQty: 50,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
        },
      ],
    },
    {
      id: 63,
      name: "Men Formal Shirt Wholesale",
      category: "apparel",
      subcategory: "men wear",
      price: 699,
      minQty: 60,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1520975682071-a8a463a1c9d2",
    },
    {
      id: 64,
      name: "Men Polo T-Shirts Bulk",
      category: "apparel",
      subcategory: "men wear",
      price: 399,
      minQty: 80,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    },
    {
      id: 65,
      name: "Men Hoodie Winter",
      category: "apparel",
      subcategory: "men wear",
      price: 999,
      minQty: 40,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
    },
    {
      id: 66,
      name: "Men Track Pants Wholesale",
      category: "apparel",
      subcategory: "men wear",
      price: 549,
      minQty: 50,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
    },
    {
      id: 67,
      name: "Men Cotton Shorts Bulk",
      category: "apparel",
      subcategory: "men wear",
      price: 299,
      minQty: 70,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
    },
    {
      id: 68,
      name: "Men Innerwear Pack",
      category: "apparel",
      subcategory: "men wear",
      price: 199,
      minQty: 120,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    },
    {
      id: 69,
      name: "Men Socks Pack Wholesale",
      category: "apparel",
      subcategory: "men wear",
      price: 99,
      minQty: 300,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    },
    {
      id: 70,
      name: "Men Jacket Lightweight",
      category: "apparel",
      subcategory: "men wear",
      price: 1299,
      minQty: 25,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1520975733722-8b1e2d1e8f20",
    },

    {
      id: 71,
      name: "Women Casual Kurti",
      category: "apparel",
      subcategory: "women wear",
      price: 499,
      minQty: 80,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
      isTopProduct: true,
      similarProducts: [
        {
          id: 72,
          name: "Women Cotton Saree",
          category: "apparel",
          subcategory: "women wear",
          price: 799,
          minQty: 40,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a45a",
        },
        {
          id: 74,
          name: "Women Tunic Tops",
          category: "apparel",
          subcategory: "women wear",
          price: 399,
          minQty: 70,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
        },
      ],
    },
    {
      id: 72,
      name: "Women Cotton Saree",
      category: "apparel",
      subcategory: "women wear",
      price: 799,
      minQty: 40,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a45a",
      isTopProduct: true,
      similarProducts: [
        {
          id: 73,
          name: "Women Leggings Bulk",
          category: "apparel",
          subcategory: "women wear",
          price: 249,
          minQty: 100,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
        },
        {
          id: 79,
          name: "Women Denim Jeans",
          category: "apparel",
          subcategory: "women wear",
          price: 999,
          minQty: 40,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
        },
      ],
    },
    {
      id: 73,
      name: "Women Leggings Bulk",
      category: "apparel",
      subcategory: "women wear",
      price: 249,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
    },
    {
      id: 74,
      name: "Women Tunic Tops",
      category: "apparel",
      subcategory: "women wear",
      price: 399,
      minQty: 70,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
    },
    {
      id: 75,
      name: "Women Nightwear Set",
      category: "apparel",
      subcategory: "women wear",
      price: 599,
      minQty: 60,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a45a",
    },
    {
      id: 76,
      name: "Women Office Shirt",
      category: "apparel",
      subcategory: "women wear",
      price: 549,
      minQty: 60,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a45a",
    },
    {
      id: 77,
      name: "Women Hoodie Winter",
      category: "apparel",
      subcategory: "women wear",
      price: 1099,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a45a",
    },
    {
      id: 78,
      name: "Women Dupatta Set",
      category: "apparel",
      subcategory: "women wear",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
    },
    {
      id: 79,
      name: "Women Denim Jeans",
      category: "apparel",
      subcategory: "women wear",
      price: 999,
      minQty: 40,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
    },
    {
      id: 80,
      name: "Women Socks Pack",
      category: "apparel",
      subcategory: "women wear",
      price: 99,
      minQty: 300,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
    },

    {
      id: 81,
      name: "Kids Printed Dress",
      category: "apparel",
      subcategory: "kids wear",
      price: 399,
      minQty: 60,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
      isTopProduct: true,
      similarProducts: [
        {
          id: 82,
          name: "Kids T-Shirts Pack",
          category: "apparel",
          subcategory: "kids wear",
          price: 249,
          minQty: 80,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
        },
        {
          id: 83,
          name: "Kids Shorts Wholesale",
          category: "apparel",
          subcategory: "kids wear",
          price: 199,
          minQty: 100,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
        },
      ],
    },
    {
      id: 82,
      name: "Kids T-Shirts Pack",
      category: "apparel",
      subcategory: "kids wear",
      price: 249,
      minQty: 80,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
      isTopProduct: true,
      similarProducts: [
        {
          id: 84,
          name: "Kids Hoodie Winter",
          category: "apparel",
          subcategory: "kids wear",
          price: 599,
          minQty: 50,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
        },
        {
          id: 86,
          name: "Kids Nightwear Set",
          category: "apparel",
          subcategory: "kids wear",
          price: 349,
          minQty: 70,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
        },
      ],
    },
    {
      id: 83,
      name: "Kids Shorts Wholesale",
      category: "apparel",
      subcategory: "kids wear",
      price: 199,
      minQty: 100,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 84,
      name: "Kids Hoodie Winter",
      category: "apparel",
      subcategory: "kids wear",
      price: 599,
      minQty: 50,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 85,
      name: "Kids School Socks Pack",
      category: "apparel",
      subcategory: "kids wear",
      price: 99,
      minQty: 250,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 86,
      name: "Kids Nightwear Set",
      category: "apparel",
      subcategory: "kids wear",
      price: 349,
      minQty: 70,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 87,
      name: "Kids Party Dress",
      category: "apparel",
      subcategory: "kids wear",
      price: 699,
      minQty: 40,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 88,
      name: "Kids Cotton Vest Pack",
      category: "apparel",
      subcategory: "kids wear",
      price: 149,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 89,
      name: "Kids Denim Jeans",
      category: "apparel",
      subcategory: "kids wear",
      price: 499,
      minQty: 60,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
    },
    {
      id: 90,
      name: "Kids Cap & Hat Set",
      category: "apparel",
      subcategory: "kids wear",
      price: 129,
      minQty: 200,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    },
  ],

  hardware: [
    {
      id: 91,
      name: "Electric Drill Machine",
      category: "hardware",
      subcategory: "tools",
      price: 2499,
      minQty: 10,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789",
      isTopProduct: true,
      similarProducts: [
        {
          id: 92,
          name: "Complete Tool Kit Set",
          category: "hardware",
          subcategory: "tools",
          price: 1499,
          minQty: 15,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
        },
        {
          id: 93,
          name: "Adjustable Wrench Set",
          category: "hardware",
          subcategory: "tools",
          price: 799,
          minQty: 30,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
        },
      ],
    },
    {
      id: 92,
      name: "Complete Tool Kit Set",
      category: "hardware",
      subcategory: "tools",
      price: 1499,
      minQty: 15,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
      isTopProduct: true,
      similarProducts: [
        {
          id: 94,
          name: "Screwdriver Set 12 pcs",
          category: "hardware",
          subcategory: "tools",
          price: 499,
          minQty: 50,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
        },
        {
          id: 95,
          name: "Hammer Fiberglass Handle",
          category: "hardware",
          subcategory: "tools",
          price: 299,
          minQty: 80,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
        },
      ],
    },
    {
      id: 93,
      name: "Adjustable Wrench Set",
      category: "hardware",
      subcategory: "tools",
      price: 799,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 94,
      name: "Screwdriver Set 12 pcs",
      category: "hardware",
      subcategory: "tools",
      price: 499,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 95,
      name: "Hammer Fiberglass Handle",
      category: "hardware",
      subcategory: "tools",
      price: 299,
      minQty: 80,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 96,
      name: "Measuring Tape 5m",
      category: "hardware",
      subcategory: "tools",
      price: 99,
      minQty: 200,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 97,
      name: "Allen Key Set",
      category: "hardware",
      subcategory: "tools",
      price: 149,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 98,
      name: "Tool Box Plastic",
      category: "hardware",
      subcategory: "tools",
      price: 599,
      minQty: 30,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 99,
      name: "Safety Gloves Pack",
      category: "hardware",
      subcategory: "tools",
      price: 199,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 100,
      name: "Protective Goggles",
      category: "hardware",
      subcategory: "tools",
      price: 149,
      minQty: 120,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 93,
      name: "Adjustable Wrench Set",
      category: "hardware",
      subcategory: "tools",
      price: 799,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 94,
      name: "Screwdriver Set 12 pcs",
      category: "hardware",
      subcategory: "tools",
      price: 499,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 95,
      name: "Hammer Fiberglass Handle",
      category: "hardware",
      subcategory: "tools",
      price: 299,
      minQty: 80,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 96,
      name: "Measuring Tape 5m",
      category: "hardware",
      subcategory: "tools",
      price: 99,
      minQty: 200,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 97,
      name: "Allen Key Set",
      category: "hardware",
      subcategory: "tools",
      price: 149,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 98,
      name: "Tool Box Plastic",
      category: "hardware",
      subcategory: "tools",
      price: 599,
      minQty: 30,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
    {
      id: 99,
      name: "Safety Gloves Pack",
      category: "hardware",
      subcategory: "tools",
      price: 199,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    {
      id: 100,
      name: "Protective Goggles",
      category: "hardware",
      subcategory: "tools",
      price: 149,
      minQty: 120,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
  ],

  fmcg: [
    {
      id: 101,
      name: "Herbal Bath Soap Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 120,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600180758890-6b94519a8ba6",
      isTopProduct: true,
      similarProducts: [
        {
          id: 103,
          name: "Toothpaste Family Pack",
          category: "fmcg",
          subcategory: "personal care",
          price: 99,
          minQty: 300,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
        },
        {
          id: 104,
          name: "Hand Sanitizer 500ml",
          category: "fmcg",
          subcategory: "personal care",
          price: 79,
          minQty: 200,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f",
        },
      ],
    },
    {
      id: 102,
      name: "Shampoo Sachets Bulk",
      category: "fmcg",
      subcategory: "personal care",
      price: 2,
      minQty: 1000,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
      isTopProduct: true,
      similarProducts: [
        {
          id: 105,
          name: "Face Wash Bulk",
          category: "fmcg",
          subcategory: "personal care",
          price: 149,
          minQty: 150,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
        },
        {
          id: 106,
          name: "Body Lotion 200ml",
          category: "fmcg",
          subcategory: "personal care",
          price: 199,
          minQty: 120,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
        },
      ],
    },
    {
      id: 103,
      name: "Toothpaste Family Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 99,
      minQty: 300,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
    },
    {
      id: 104,
      name: "Hand Sanitizer 500ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 79,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f",
    },
    {
      id: 105,
      name: "Face Wash Bulk",
      category: "fmcg",
      subcategory: "personal care",
      price: 149,
      minQty: 150,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 106,
      name: "Body Lotion 200ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 199,
      minQty: 120,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 107,
      name: "Hair Oil 100ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 99,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
    },
    {
      id: 108,
      name: "Disposable Razors Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 49,
      minQty: 400,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600180758890-6b94519a8ba6",
    },
    {
      id: 109,
      name: "Talcum Powder 100g",
      category: "fmcg",
      subcategory: "personal care",
      price: 59,
      minQty: 250,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 110,
      name: "Wet Wipes Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 39,
      minQty: 500,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f",
    },
    {
      id: 103,
      name: "Toothpaste Family Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 99,
      minQty: 300,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
    },
    {
      id: 104,
      name: "Hand Sanitizer 500ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 79,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f",
    },
    {
      id: 105,
      name: "Face Wash Bulk",
      category: "fmcg",
      subcategory: "personal care",
      price: 149,
      minQty: 150,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 106,
      name: "Body Lotion 200ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 199,
      minQty: 120,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 107,
      name: "Hair Oil 100ml",
      category: "fmcg",
      subcategory: "personal care",
      price: 99,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
    },
    {
      id: 108,
      name: "Disposable Razors Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 49,
      minQty: 400,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600180758890-6b94519a8ba6",
    },
    {
      id: 109,
      name: "Talcum Powder 100g",
      category: "fmcg",
      subcategory: "personal care",
      price: 59,
      minQty: 250,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
    },
    {
      id: 110,
      name: "Wet Wipes Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 39,
      minQty: 500,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f",
    },
  ],

  furniture: [
    {
      id: 111,
      name: "Office Chair Ergonomic",
      category: "furniture",
      subcategory: "office",
      price: 4999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
      isTopProduct: true,
      similarProducts: [
        {
          id: 112,
          name: "Office Desk Wooden",
          category: "furniture",
          subcategory: "office",
          price: 7999,
          minQty: 3,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1598300056393-4aac492f4344",
        },
        {
          id: 115,
          name: "Mesh Office Chair",
          category: "furniture",
          subcategory: "office",
          price: 5999,
          minQty: 3,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        },
      ],
    },
    {
      id: 112,
      name: "Office Desk Wooden",
      category: "furniture",
      subcategory: "office",
      price: 7999,
      minQty: 3,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1598300056393-4aac492f4344",
      isTopProduct: true,
      similarProducts: [
        {
          id: 114,
          name: "Office Drawer Unit",
          category: "furniture",
          subcategory: "office",
          price: 3999,
          minQty: 5,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
        },
        {
          id: 118,
          name: "Office Bookshelf",
          category: "furniture",
          subcategory: "office",
          price: 6999,
          minQty: 2,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
        },
      ],
    },
    {
      id: 113,
      name: "Conference Table Large",
      category: "furniture",
      subcategory: "office",
      price: 24999,
      minQty: 1,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    {
      id: 114,
      name: "Office Drawer Unit",
      category: "furniture",
      subcategory: "office",
      price: 3999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 115,
      name: "Mesh Office Chair",
      category: "furniture",
      subcategory: "office",
      price: 5999,
      minQty: 3,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
    {
      id: 116,
      name: "Office Visitor Chair",
      category: "furniture",
      subcategory: "office",
      price: 2499,
      minQty: 10,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
    {
      id: 117,
      name: "Laptop Table Portable",
      category: "furniture",
      subcategory: "office",
      price: 1299,
      minQty: 20,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1598300056393-4aac492f4344",
    },
    {
      id: 118,
      name: "Office Bookshelf",
      category: "furniture",
      subcategory: "office",
      price: 6999,
      minQty: 2,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 119,
      name: "Desk Lamp LED",
      category: "furniture",
      subcategory: "office",
      price: 499,
      minQty: 50,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
    },
    {
      id: 120,
      name: "Office Foot Rest",
      category: "furniture",
      subcategory: "office",
      price: 599,
      minQty: 30,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },

    {
      id: 121,
      name: "Wooden Study Table",
      category: "furniture",
      subcategory: "home",
      price: 6999,
      minQty: 3,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1598300056393-4aac492f4344",
      isTopProduct: true,
      similarProducts: [
        {
          id: 122,
          name: "Sofa Set 3+1+1",
          category: "furniture",
          subcategory: "home",
          price: 29999,
          minQty: 1,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        },
        {
          id: 123,
          name: "Dining Table 4 Seater",
          category: "furniture",
          subcategory: "home",
          price: 17999,
          minQty: 1,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
        },
      ],
    },
    {
      id: 122,
      name: "Sofa Set 3+1+1",
      category: "furniture",
      subcategory: "home",
      price: 29999,
      minQty: 1,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
      isTopProduct: true,
      similarProducts: [
        {
          id: 124,
          name: "Wardrobe 3 Door",
          category: "furniture",
          subcategory: "home",
          price: 23999,
          minQty: 1,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        },
        {
          id: 129,
          name: "Coffee Table",
          category: "furniture",
          subcategory: "home",
          price: 3999,
          minQty: 3,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        },
      ],
    },
    {
      id: 123,
      name: "Dining Table 4 Seater",
      category: "furniture",
      subcategory: "home",
      price: 17999,
      minQty: 1,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 124,
      name: "Wardrobe 3 Door",
      category: "furniture",
      subcategory: "home",
      price: 23999,
      minQty: 1,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    {
      id: 125,
      name: "Bedside Table",
      category: "furniture",
      subcategory: "home",
      price: 2999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 126,
      name: "Bookshelf Home",
      category: "furniture",
      subcategory: "home",
      price: 5999,
      minQty: 2,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 127,
      name: "TV Unit Cabinet",
      category: "furniture",
      subcategory: "home",
      price: 8999,
      minQty: 2,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 128,
      name: "Shoe Rack Wooden",
      category: "furniture",
      subcategory: "home",
      price: 2499,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 129,
      name: "Coffee Table",
      category: "furniture",
      subcategory: "home",
      price: 3999,
      minQty: 3,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    {
      id: 130,
      name: "Bean Bag Chair",
      category: "furniture",
      subcategory: "home",
      price: 1999,
      minQty: 10,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
    {
      id: 122,
      name: "Sofa Set 3+1+1",
      category: "furniture",
      subcategory: "home",
      price: 29999,
      minQty: 1,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
    {
      id: 123,
      name: "Dining Table 4 Seater",
      category: "furniture",
      subcategory: "home",
      price: 17999,
      minQty: 1,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 124,
      name: "Wardrobe 3 Door",
      category: "furniture",
      subcategory: "home",
      price: 23999,
      minQty: 1,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    {
      id: 125,
      name: "Bedside Table",
      category: "furniture",
      subcategory: "home",
      price: 2999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 126,
      name: "Bookshelf Home",
      category: "furniture",
      subcategory: "home",
      price: 5999,
      minQty: 2,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 127,
      name: "TV Unit Cabinet",
      category: "furniture",
      subcategory: "home",
      price: 8999,
      minQty: 2,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 128,
      name: "Shoe Rack Wooden",
      category: "furniture",
      subcategory: "home",
      price: 2499,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693314121-9f1d8f2c54d3",
    },
    {
      id: 129,
      name: "Coffee Table",
      category: "furniture",
      subcategory: "home",
      price: 3999,
      minQty: 3,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    {
      id: 130,
      name: "Bean Bag Chair",
      category: "furniture",
      subcategory: "home",
      price: 1999,
      minQty: 10,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
  ],

  automotive: [
    {
      id: 131,
      name: "Car Seat Cover Set",
      category: "automotive",
      subcategory: "spare parts",
      price: 1999,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2",
      isTopProduct: true,
      similarProducts: [
        {
          id: 132,
          name: "Car Floor Mat Set",
          category: "automotive",
          subcategory: "spare parts",
          price: 1299,
          minQty: 30,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023",
        },
        {
          id: 133,
          name: "Car Wiper Blades Pack",
          category: "automotive",
          subcategory: "spare parts",
          price: 299,
          minQty: 100,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3",
        },
      ],
    },
    {
      id: 132,
      name: "Car Floor Mat Set",
      category: "automotive",
      subcategory: "spare parts",
      price: 1299,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023",
      isTopProduct: true,
      similarProducts: [
        {
          id: 134,
          name: "Car Battery 12V",
          category: "automotive",
          subcategory: "spare parts",
          price: 4999,
          minQty: 5,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
        },
        {
          id: 135,
          name: "Engine Oil 1L",
          category: "automotive",
          subcategory: "spare parts",
          price: 399,
          minQty: 50,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1616627988364-0d5d6f6e0f64",
        },
      ],
    },
    {
      id: 133,
      name: "Car Wiper Blades Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 299,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3",
    },
    {
      id: 134,
      name: "Car Battery 12V",
      category: "automotive",
      subcategory: "spare parts",
      price: 4999,
      minQty: 5,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 135,
      name: "Engine Oil 1L",
      category: "automotive",
      subcategory: "spare parts",
      price: 399,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1616627988364-0d5d6f6e0f64",
    },
    {
      id: 136,
      name: "Car Air Freshener Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 99,
      minQty: 200,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    },
    {
      id: 137,
      name: "Car Mobile Holder",
      category: "automotive",
      subcategory: "spare parts",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1493238792000-8113da705763",
    },
    {
      id: 138,
      name: "Car Vacuum Cleaner",
      category: "automotive",
      subcategory: "spare parts",
      price: 1499,
      minQty: 15,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 139,
      name: "Tyre Inflator Portable",
      category: "automotive",
      subcategory: "spare parts",
      price: 1999,
      minQty: 10,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 140,
      name: "Car Cleaning Cloth Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 79,
      minQty: 300,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    },
    {
      id: 132,
      name: "Car Floor Mat Set",
      category: "automotive",
      subcategory: "spare parts",
      price: 1299,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023",
    },
    {
      id: 133,
      name: "Car Wiper Blades Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 299,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3",
    },
    {
      id: 134,
      name: "Car Battery 12V",
      category: "automotive",
      subcategory: "spare parts",
      price: 4999,
      minQty: 5,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 135,
      name: "Engine Oil 1L",
      category: "automotive",
      subcategory: "spare parts",
      price: 399,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1616627988364-0d5d6f6e0f64",
    },
    {
      id: 136,
      name: "Car Air Freshener Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 99,
      minQty: 200,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    },
    {
      id: 137,
      name: "Car Mobile Holder",
      category: "automotive",
      subcategory: "spare parts",
      price: 199,
      minQty: 150,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1493238792000-8113da705763",
    },
    {
      id: 138,
      name: "Car Vacuum Cleaner",
      category: "automotive",
      subcategory: "spare parts",
      price: 1499,
      minQty: 15,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 139,
      name: "Tyre Inflator Portable",
      category: "automotive",
      subcategory: "spare parts",
      price: 1999,
      minQty: 10,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1542362567-b07e54358753",
    },
    {
      id: 140,
      name: "Car Cleaning Cloth Pack",
      category: "automotive",
      subcategory: "spare parts",
      price: 79,
      minQty: 300,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    },
  ],

  packaging: [
    {
      id: 141,
      name: "Corrugated Boxes Bulk",
      category: "packaging",
      subcategory: "boxes",
      price: 30,
      minQty: 500,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
      isTopProduct: true,
      similarProducts: [
        {
          id: 143,
          name: "Mailer Boxes Premium",
          category: "packaging",
          subcategory: "boxes",
          price: 18,
          minQty: 1000,
          supplier: "Trusted Supplier",
          image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
        },
        {
          id: 144,
          name: "Packing Tape Brown",
          category: "packaging",
          subcategory: "boxes",
          price: 35,
          minQty: 200,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
        },
      ],
    },
    {
      id: 142,
      name: "Carton Boxes Shipping",
      category: "packaging",
      subcategory: "boxes",
      price: 22,
      minQty: 800,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
      isTopProduct: true,
      similarProducts: [
        {
          id: 145,
          name: "Bubble Wrap Roll",
          category: "packaging",
          subcategory: "boxes",
          price: 499,
          minQty: 20,
          supplier: "Gold Supplier",
          image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
        },
        {
          id: 147,
          name: "Stretch Film Roll",
          category: "packaging",
          subcategory: "boxes",
          price: 399,
          minQty: 30,
          supplier: "Verified Supplier",
          image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
        },
      ],
    },
    {
      id: 143,
      name: "Mailer Boxes Premium",
      category: "packaging",
      subcategory: "boxes",
      price: 18,
      minQty: 1000,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 144,
      name: "Packing Tape Brown",
      category: "packaging",
      subcategory: "boxes",
      price: 35,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 145,
      name: "Bubble Wrap Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 499,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 146,
      name: "Foam Sheet Packing",
      category: "packaging",
      subcategory: "boxes",
      price: 299,
      minQty: 50,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 147,
      name: "Stretch Film Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 399,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 148,
      name: "Strapping Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 549,
      minQty: 15,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 149,
      name: "Packing Labels Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 149,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 150,
      name: "Edge Protector Corners",
      category: "packaging",
      subcategory: "boxes",
      price: 99,
      minQty: 300,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 142,
      name: "Carton Boxes Shipping",
      category: "packaging",
      subcategory: "boxes",
      price: 22,
      minQty: 800,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 143,
      name: "Mailer Boxes Premium",
      category: "packaging",
      subcategory: "boxes",
      price: 18,
      minQty: 1000,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 144,
      name: "Packing Tape Brown",
      category: "packaging",
      subcategory: "boxes",
      price: 35,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 145,
      name: "Bubble Wrap Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 499,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 146,
      name: "Foam Sheet Packing",
      category: "packaging",
      subcategory: "boxes",
      price: 299,
      minQty: 50,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 147,
      name: "Stretch Film Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 399,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 148,
      name: "Strapping Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 549,
      minQty: 15,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 149,
      name: "Packing Labels Roll",
      category: "packaging",
      subcategory: "boxes",
      price: 149,
      minQty: 100,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
    {
      id: 150,
      name: "Edge Protector Corners",
      category: "packaging",
      subcategory: "boxes",
      price: 99,
      minQty: 300,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
  ],
};